package polybius.common.models

enum class MessageType {
    EXECUTOR_CONNECTED,
    CLIENT_CONNECTED,

    SERVER_TASK_ADDED,
    SERVER_TASK_REMOVED,

    EXECUTOR_IDLE,
    EXECUTOR_TASK_ACCEPTED,
    EXECUTOR_TASK_PLAYING,
    EXECUTOR_TASK_PAUSED,
    EXECUTOR_TASK_ERROR,

    SERVER_PAUSE,
    SERVER_PLAY,

    ERROR,
}